# Icons diameter after conversion
iconSidePx: 128

# Default units from Wikiloc
WLDistanceUnit: "mi"
WLElevationUnit: "ft"

# Measurement system to use in the updates. Use "metric" or "imperial"
mesSys: "metric"

# Router endpoints
endpoints:
  updates: "/api/v1/overlay"
  legend: "/api/v1/gen-img"
  static: "/static"

# Google Chart base URL
gChartBaseURL: "https://chart.apis.google.com/chart?chst=d_text_outline&chld=000000|20|l|ffffff|b|"

redirectPage: "https://jonamat.github.io/wikiloc-earth-layer/"