# Icons diameter after conversion
iconSidePx: 128

# Measurement system to use in the updates. Use "metric" or "imperial"
mesSys: "metric"

# Limit for the trails loaded in Google Earth
trailsLimit: 100

# Delay after stop
stopDelay: 2.0 # sec

# Router endpoints
endpoints:
  init: "/api/v1/init"
  updates: "/api/v1/updates"
  legend: "/api/v1/gen-img"
  static: "/static"

# Google Chart base URL
gChartBaseURL: "https://chart.apis.google.com/chart?chst=d_text_outline&chld=000000|20|l|ffffff|b|"

# Destination page routed by navigating in the root
redirectPage: "https://jonamat.github.io/wikiloc-earth-layer/"

# HTTP client settings
connectionAttempts: 3
connectionTimeout: 10 # sec
retryDelay: 4 # sec
