version: '3.7'

services:
  wikiloc-earth-layar:
    image: jonamat/wikiloc-earth-layer
    environment:
      PROTOCOL: https
      HOST: wikiloc-earth-layer.jonamat.cloud
      PORT: 80
    networks:
      - caddy
    labels:
      caddy: wikiloc-earth-layer.jonamat.cloud
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
