name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Get latest tag"
        run: echo "RELEASE_VERSION=${git describe --tags}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: |
            HOST=wikiloc-earth-layer.jonamat.cloud
            PORT=80
            PROTOCOL=http
          tags: |
            jonamat/wikiloc-earth-layer:latest
            jonamat/wikiloc-earth-layer:${{ env.RELEASE_VERSION }}
